remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme 
title: Between Reality and Documentary
description: A Historical Representation of Gaza Refugees in Colonial, Humanitarian and Palestinian Documentary Film
